version: '3.7'
services:
  flickr_client:
    container_name: flickr_client
    build:
      context: .
      dockerfile: flickr/Dockerfile
    image: 'witw/flickr-client'
    secrets:
      - flickr_api_key
      - flickr_api_secret
secrets:
  flickr_api_key:
    file: ./flickr_api_key.txt
  flickr_api_secret:
    file: ./flickr_api_secret.txt